#!/bin/sh

if [ -e /etc/ssh/sshd_config ] ; then
  sed -e "s|^#PermitRootLogin.*|PermitRootLogin yes|g" \
      -e "s|^PasswordAuthentication.*|PasswordAuthentication yes|g" \
      -i /etc/ssh/sshd_config
fi

